language: php
php:
 - '7.1'
 - '7.2'
 - '7.3'
 - '7.4'

install:
 - cd ./projects/tests/
 - rm -f composer.lock
 - rm -rf vendor/
 - composer clearcache
 - composer install

script:
- ./vendor/bin/phpunit
